version: '2'
services:
  redis:
    image: redis:4-alpine
    ports:
      - 6379:6379

  mongo:
    image: mongo:3.4.10
    ports:
      - 27017:27017

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src/
    depends_on:
      - mongo
      - redis
    command: npm run start:worker
    env_file:
      - .env

  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src/
    ports:
      - 8080:8080
    depends_on:
      - mongo
    command: npm run start:server
    env_file:
      - .env

