version: '2'
services:
  redis:
    image: redis:4-alpine
  mongo:
    image: mongo:3.4.10
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev_server
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://mongo/database
      REDIS_URI: redis
      DEBUG: App*
      PORT: 8080
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - redis
    volumes:
     - .:/usr/src/app
     - /usr/src/app/node_modules
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev_worker
    tty: true
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://mongo/database
      REDIS_URI: redis
      DEBUG: App*
    depends_on:
      - mongo
      - redis
    volumes:
     - .:/usr/src/app
     - /usr/src/app/node_modules